### ISSUE TITLE
CVE-2020-15999

### ISSUE THREAD

**Issue by TheBlueMatt** [PistonDevelopers/freetype-sys#91]
According to the link from the freetype site (https://sourceforge.net/projects/freetype/files/freetype2/2.10.4/), the actively-exploited-against-chrome-users CVE was introduced in 2.6, which it appears is still being shipped (at least for android?) here. Seems like the patch should be backported or freetype updated.

**Comment by bvssvni** [comment]
cc @chrisduerr

**Comment by chrisduerr** [comment]
Based on the CVE description it looks like this could be a problem if another user controls the font which is loaded by the user. While for most usecases that shouldn't be the end of the world, Browsers like servo should **really** be concerned as far as I can tell.

Generally the FreeType compilation is done for Android Servo, which I am not affiliated with. But since I provided the code, I'm happy to try and upgrade FreeType and verify that skia still builds correctly with it. Thanks for the ping.

**Comment by chrisduerr** [comment]
Actually it seems like it is compiled using `WITH_PNG=OFF`, while FreeType explicitly mentions that `FT_CONFIG_OPTION_USE_PNG` is the problem. So this crate might be unaffected.

**Comment by chrisduerr** [comment]
I've just made sure and by using `WITH_PNG=OFF` we do indeed disable loading the `PNG` library which in turn [does not set](https://github.com/PistonDevelopers/freetype-sys/blob/879a236994efd5d2caed156dad7db742a509294a/freetype2/CMakeLists.txt#L247-L250) the `FT_CONFIG_OPTION_USE_PNG` option [in the header](https://github.com/PistonDevelopers/freetype-sys/blob/879a236994efd5d2caed156dad7db742a509294a/freetype2/include/freetype/config/ftoption.h#L228).

So as far as the CVE is concerned, it should be all good I think. But of course I can still check if an update is possible. That would be a breaking change though.

**Comment by TheBlueMatt** [comment]
Awesome, thanks for checking! I have no horse in this race, in that case :).
